

resources:
  repositories:
  - repository: FreeRDP
    type: git
    name: DxgkLinux/FreeRDP
    ref: working
  - repository: weston
    type: git
    name: DxgkLinux/weston
    ref: working
  - repository: pulseaudio
    type: git
    name: DxgkLinux/pulseaudio
    ref: working

trigger:
  - working
  
pool:
  vmImage: 'ubuntu-latest'
  
steps:
  - checkout: FreeRDP
  - checkout: weston
  - checkout: pulseaudio
  - checkout: self

  - script: sudo apt-get update && sudo apt-get install --no-install-recommends -y
            squashfs-tools
    displayName: 'Install Dependencies'

  - task: DockerInstaller@0
    inputs:
      dockerVersion: '17.09.0-ce'
  
  - script: mv FreeRDP/ SystemDistro/vendor/ &&
            mv weston/ SystemDistro/vendor/ &&
            mv pulseaudio/ SystemDistro/vendor/

    displayName: 'Move sub projects (FreeRDP, Weston)'

  - script: docker build -t wsl-system-distro ./SystemDistro
