

resources:
  repositories:
  - repository: FreeRDP
    type: git
    name: DxgkLinux/FreeRDP
    ref: working
  - repository: weston
    type: git
    name: DxgkLinux/weston
    ref: working
  - repository: pulseaudio
    type: git
    name: DxgkLinux/pulseaudio
    ref: working

trigger:
  - working
  
pool:
  vmImage: 'ubuntu-latest'
  
steps:
  - checkout: FreeRDP
  - checkout: weston
  - checkout: pulseaudio
  - checkout: self

  - script: git clone --branch v1.0.0 https://github.com/AgentD/squashfs-tools-ng.git &&
            cd squashfs-tools-ng &&
            ./autogen.sh &&
            ./configure &&
            make && sudo make install &&
            cd ..
    displayName: 'Build squashfs-tools-ng since is not supported on 18.04 using apt'

  - task: DockerInstaller@0
    inputs:
      dockerVersion: '17.09.0-ce'
  
  - script: mv FreeRDP/ SystemDistro/vendor/ &&
            mv weston/ SystemDistro/vendor/ &&
            mv pulseaudio/ SystemDistro/vendor/
    displayName: 'Move sub projects (FreeRDP, Weston)'

  - script: docker build -t wsl-system-distro ./SystemDistro
    displayName: 'Create docker image'

  - script:   export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH &&
              tar2sqfs $(Agent.BuildDirectory)/system.squashfs < docker export `docker run -d wsl-system-distro`
    displayName: 'Create SquashFS'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish SquashFS artifact'
    inputs:
      targetPath: $(Agent.BuildDirectory)/system.squashfs
      artifact: 'system.squashfs'
      publishLocation: 'pipeline'