resources:
  repositories:
  - repository: wayland
    type: git
    name: DxgkLinux/wayland
    ref: working
  - repository: FreeRDP
    type: git
    name: DxgkLinux/FreeRDP
    ref: working
  - repository: weston
    type: git
    name: DxgkLinux/weston
    ref: working
  - repository: pulseaudio
    type: git
    name: DxgkLinux/pulseaudio
    ref: working
  - repository: sharedguestalloc
    type: git
    name: DxgkLinux/sharedguestalloc
    ref: master

trigger:
  - working
jobs:
- job: 'Build_Ubuntu'
  displayName: 'Build (Ubuntu)'
  variables:
    - group: 'Keys'

  pool:
    vmImage: 'ubuntu-latest'
    
  steps:
    - checkout: wayland
    - checkout: FreeRDP
    - checkout: weston
    - checkout: pulseaudio
    - checkout: sharedguestalloc
    - checkout: self

    - task: DockerInstaller@0
      inputs:
        dockerVersion: '20.10.2'
        releaseType: 'stable'
    - bash: |
            curl -L -o ~/.docker/cli-plugins/docker-buildx --create-dirs ${BUILDX_URL}
            chmod a+x ~/.docker/cli-plugins/docker-buildx
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            ~/.docker/cli-plugins/docker-buildx create --use
            ~/.docker/cli-plugins/docker-buildx inspect --bootstrap
      displayName: Prepare buildx
      env:
        BUILDX_URL: https://github.com/docker/buildx/releases/download/v0.5.1/buildx-v0.5.1.linux-amd64

    - script: |
              echo '{ "experimental": true }' | sudo tee /etc/docker/daemon.json
              sudo service docker restart
      displayName: 'Enable Docker Engine experimental '

    - script: mv wayland/ wslg/vendor/ &&
              mv FreeRDP/ wslg/vendor/ &&
              mv weston/ wslg/vendor/ &&
              mv sharedguestalloc/ wslg/vendor/ &&
              mv pulseaudio/ wslg/vendor/
      displayName: 'Move sub projects (FreeRDP, Weston)'

    - script: wget https://github.com/GitTools/GitVersion/releases/download/5.3.7/gitversion-ubuntu.18.04-x64-5.3.7.tar.gz &&
              tar -xvf gitversion-ubuntu.18.04-x64-5.3.7.tar.gz &&
              sudo mv gitversion /usr/local/bin
      displayName: 'Install GitVersion'
    
    - script: docker build -f ./wslg/Dockerfile.Mariner -t system-distro-mariner-x64 
              ./wslg 
              --build-arg WSLG_VERSION=`gitversion /targetpath ./wslg /showvariable InformationalVersion`
              --build-arg WSLG_ARCH=x86_64
      displayName: 'Create System Distro Docker image Mariner-x64'

    - script: docker export `docker create system-distro-mariner-x64` > $(Agent.BuildDirectory)/system_mariner_x64.tar
      displayName: 'Create system_mariner_x64.tar'


    - script: docker build -f ./wslg/Dockerfile -t system-distro-ubuntu-x64 
              ./wslg 
              --build-arg WSLG_VERSION=`gitversion /targetpath ./wslg /showvariable InformationalVersion`
              --build-arg WSLG_ARCH=x86_64
      displayName: 'Create System Distro Docker image Ubuntu-x64'

    - script: docker export `docker create system-distro-ubuntu-x64` > $(Agent.BuildDirectory)/system_ubuntu_x64.tar
      displayName: 'Create system_ubuntu_x64.tar'

      # TODO: Use ARM64 image from ACR
      #
    - script: echo $(docker_token) | docker login --username viniciusjarina --password-stdin
      displayName: 'Docker Login'

    - script: ~/.docker/cli-plugins/docker-buildx build -f ./wslg/Dockerfile.MarinerARM64
              --output type=tar,dest=$(Agent.BuildDirectory)/system_mariner_arm64.tar 
              --platform=linux/arm64 
              ./wslg 
              --build-arg WSLG_VERSION=`gitversion /targetpath ./wslg /showvariable InformationalVersion` 
              --build-arg WSLG_ARCH=aarch64
      displayName: 'Create system_mariner_arm64.tar'

    # - script: ~/.docker/cli-plugins/docker-buildx build -f ./wslg/Dockerfile
    #           --output type=tar,dest=$(Agent.BuildDirectory)/system_ubuntu_arm64.tar 
    #           --platform=linux/arm64 
    #           ./wslg 
    #           --build-arg WSLG_VERSION=`gitversion /targetpath ./wslg /showvariable InformationalVersion` 
    #           --build-arg WSLG_ARCH=aarch64
    #   displayName: 'Create system_ubuntu_arm64.tar'

    - script: git clone --branch v0.8.14 --single-branch https://github.com/microsoft/hcsshim.git
      displayName: 'Clone hcsshim repo for tar2ext4 tool'

    - task: Go@0
      inputs:
        command: 'custom'
        customCommand: 'run'
        arguments: 'tar2ext4.go -vhd -i $(Agent.BuildDirectory)/system_ubuntu_x64.tar -o $(Agent.BuildDirectory)/system_ubuntu_x64.vhd'
        workingDirectory: 'hcsshim/cmd/tar2ext4'
      displayName: 'Create system_ubuntu_x64.vhd'

    # - task: Go@0
    #   inputs:
    #     command: 'custom'
    #     customCommand: 'run'
    #     arguments: 'tar2ext4.go -vhd -i $(Agent.BuildDirectory)/system_ubuntu_arm64.tar -o $(Agent.BuildDirectory)/system_ubuntu_arm64.vhd'
    #     workingDirectory: 'hcsshim/cmd/tar2ext4'
    #   displayName: 'Create system_ubuntu_arm64.vhd'

    - task: Go@0
      inputs:
        command: 'custom'
        customCommand: 'run'
        arguments: 'tar2ext4.go -vhd -i $(Agent.BuildDirectory)/system_mariner_x64.tar -o $(Agent.BuildDirectory)/system_mariner_x64.vhd'
        workingDirectory: 'hcsshim/cmd/tar2ext4'
      displayName: 'Create system_mariner_x64.vhd'

    - task: Go@0
      inputs:
        command: 'custom'
        customCommand: 'run'
        arguments: 'tar2ext4.go -vhd -i $(Agent.BuildDirectory)/system_mariner_arm64.tar -o $(Agent.BuildDirectory)/system_mariner_arm64.vhd'
        workingDirectory: 'hcsshim/cmd/tar2ext4'
      displayName: 'Create system_mariner_arm64.vhd'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish system_ubuntu_x64.vhd artifact'
      inputs:
        targetPath: $(Agent.BuildDirectory)/system_ubuntu_x64.vhd
        artifact: 'system_ubuntu_x64.vhd'
        publishLocation: 'pipeline'

    # - task: PublishPipelineArtifact@1
    #   displayName: 'Publish system_ubuntu_arm64.vhd artifact'
    #   inputs:
    #     targetPath: $(Agent.BuildDirectory)/system_ubuntu_arm64.vhd
    #     artifact: 'system_ubuntu_arm64.vhd'
    #     publishLocation: 'pipeline'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish system_mariner_arm64.vhd artifact'
      inputs:
        targetPath: $(Agent.BuildDirectory)/system_mariner_arm64.vhd
        artifact: 'system_mariner_arm64.vhd'
        publishLocation: 'pipeline'

    - task: PublishPipelineArtifact@1
      displayName: 'Publish system_mariner_x64.vhd artifact'
      inputs:
        targetPath: $(Agent.BuildDirectory)/system_mariner_x64.vhd
        artifact: 'system_mariner_x64.vhd'
        publishLocation: 'pipeline'
        
- job: 'Build_Windows'
  dependsOn: 'Build_Ubuntu'
  displayName: 'Package (Windows)'
  
  pool:
    vmImage: 'windows-2019'
    demands:
    - msbuild
    - visualstudio

  steps:
  - checkout: self

  - powershell: 'Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString(''https://chocolatey.org/install.ps1''))'
    displayName: 'Install Choco'

  - script: 'choco install gitversion.portable --pre'
    displayName: 'Install GitVersion'
    
  - powershell: Invoke-WebRequest https://wixtoolset.org/downloads/v3.14.0.4118/wix314-binaries.zip -OutFile wix314-binaries.zip;
                Expand-Archive wix314-binaries.zip -DestinationPath $(Agent.BuildDirectory)\wix314-binaries
    displayName: 'Install Wix'

  - task: DownloadPipelineArtifact@2
    displayName: 'Download system_ubuntu_x64.vhd'
    inputs:
      buildType: 'current'
      artifactName: 'system_ubuntu_x64.vhd'
      targetPath: 'msi/'

  # - task: DownloadPipelineArtifact@2
  #   displayName: 'Download system_ubuntu_arm64.vhd'
  #   inputs:
  #     buildType: 'current'
  #     artifactName: 'system_ubuntu_arm64.vhd'
  #     targetPath: 'msi/'

  - task: DownloadPipelineArtifact@2
    displayName: 'Download system_mariner_x64.vhd'
    inputs:
      buildType: 'current'
      artifactName: 'system_mariner_x64.vhd'
      targetPath: 'msi/'

  - task: DownloadPipelineArtifact@2
    displayName: 'Download system_mariner_arm64.vhd'
    inputs:
      buildType: 'current'
      artifactName: 'system_mariner_arm64.vhd'
      targetPath: 'msi/'

  - task: MSBuild@1
    displayName: 'Build RDP Plugin (x64)'
    inputs:
      solution: './WSLDVCPlugin/WSLDVCPlugin.sln'
      platform: 'x64'
      configuration: 'Release'

  - task: MSBuild@1
    displayName: 'Build RDP Plugin (ARM64)'
    inputs:
      solution: './WSLDVCPlugin/WSLDVCPlugin.sln'
      platform: 'ARM64'
      configuration: 'Release'

  - script: 'MOVE WSLDVCPlugin\x64\Release\WSLDVCPlugin.dll msi\WSLDVCPlugin_x64.dll'
    displayName: 'Move plugin to msi (x64)'

  - script: 'MOVE WSLDVCPlugin\ARM64\Release\WSLDVCPlugin.dll msi\WSLDVCPlugin_ARM64.dll'
    displayName: 'Move plugin to msi (ARM64)'

  - task: PowerShell@2
    displayName: 'Update wslg.wxs version'
    inputs:
      targetType: filePath
      filePath: .\msi\updateversion.ps1
      arguments: '.\msi\wslg.wxs'
      pwsh: true

  - script: '$(Agent.BuildDirectory)\wix314-binaries\candle.exe wslg.wxs -arch x64 -dVhdFile=system_ubuntu_x64.vhd -dPlatform=x64 -o obj_ubuntu_x64\'
    workingDirectory: msi
    displayName: 'WiX Candle (Ubuntu-x64)'

  - script: '$(Agent.BuildDirectory)\wix314-binaries\light.exe obj_ubuntu_x64\wslg.wixobj -o bin\wsl_graphics_update_ubuntu_x64.msi'
    workingDirectory: msi
    displayName: 'WiX Light (Ubuntu-x64)'

  # - script: '$(Agent.BuildDirectory)\wix314-binaries\candle.exe wslg.wxs -arch arm64 -dVhdFile=system_ubuntu_arm64.vhd -dPlatform=arm64 -o obj_ubuntu_arm64\'
  #   workingDirectory: msi
  #   displayName: 'WiX Candle (Ubuntu-arm64)'

  # - script: '$(Agent.BuildDirectory)\wix314-binaries\light.exe obj_ubuntu_arm64\wslg.wixobj -o bin\wsl_graphics_update_arm64.msi'
  #   workingDirectory: msi
  #   displayName: 'WiX Light (Ubuntu-arm64)'

  - script: '$(Agent.BuildDirectory)\wix314-binaries\candle.exe wslg.wxs -arch x64 -dVhdFile=system_mariner_x64.vhd -dPlatform=x64 -o obj_mariner_x64\'
    workingDirectory: msi
    displayName: 'WiX Candle (Mariner-x64)'

  - script: '$(Agent.BuildDirectory)\wix314-binaries\light.exe obj_mariner_x64\wslg.wixobj -o bin\wsl_graphics_update_x64.msi'
    workingDirectory: msi
    displayName: 'WiX Light (Mariner-x64)'

  - script: '$(Agent.BuildDirectory)\wix314-binaries\candle.exe wslg.wxs -arch arm64 -dVhdFile=system_mariner_arm64.vhd -dPlatform=arm64 -o obj_mariner_arm64\'
    workingDirectory: msi
    displayName: 'WiX Candle (Mariner-arm64)'

  - script: '$(Agent.BuildDirectory)\wix314-binaries\light.exe obj_mariner_arm64\wslg.wixobj -o bin\wsl_graphics_update_mariner_arm64.msi'
    workingDirectory: msi
    displayName: 'WiX Light (Mariner-arm64)'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish WSLG installer (Ubuntu)'
    inputs:
      targetPath: msi/bin/wsl_graphics_update_ubuntu_x64.msi
      artifact: 'wsl_graphics_update_ubuntu_x64.msi'
      publishLocation: 'pipeline'

  # - task: PublishPipelineArtifact@1
  #   displayName: 'Publish WSLG installer (Ubuntu)'
  #   inputs:
  #     targetPath: msi/bin/wsl_graphics_update_arm64.msi
  #     artifact: 'wsl_graphics_update_arm64.msi'
  #     publishLocation: 'pipeline'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish WSLG installer (Mariner)'
    inputs:
      targetPath: msi/bin/wsl_graphics_update_x64.msi
      artifact: 'wsl_graphics_update_x64.msi'
      publishLocation: 'pipeline'

  - task: PublishPipelineArtifact@1
    displayName: 'Publish WSLG installer (Mariner) ARM64'
    inputs:
      targetPath: msi/bin/wsl_graphics_update_mariner_arm64.msi
      artifact: 'wsl_graphics_update_mariner_arm64.msi'
      publishLocation: 'pipeline'